AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Peering Inviter Create
# ------------------------------------------------------------#
#  Metadata
# ------------------------------------------------------------#
Metadata: 
  "AWS::CloudFormation::Interface": 
    ParameterGroups: 
      - Label: 
          default: "VPCPeering Configuration"
        Parameters: 
          - UserName

    ParameterLabels: 
      UserName: 
        default: "TagsValue UserName"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  UserName:
    Type: String
    Default: "inamura"

# ------------------------------------------------------------#
#  Resources
# ------------------------------------------------------------#
Resources:
# ------------------------------------------------------------#
#  VPCPeering
# ------------------------------------------------------------#
  VPCPeer: 
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      VpcId: !ImportValue cfn-network-A-vpc
      PeerVpcId: !ImportValue cfn-network-B-vpc
      Tags:
        - Key: "User"
          Value: !Ref UserName
